import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { CanvasProvider } from "@/contexts/CanvasContext";
import { ColorPickerProvider } from "@/contexts/ColorPickerContext";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ColorPickerProvider>
          <CanvasProvider>
            <SidebarProvider>
              <AppSidebar />
              {/* taking width of entire viewport */}
              <main className="w-full">
                {/* <SidebarTrigger /> */}

                {children}
              </main>
            </SidebarProvider>
          </CanvasProvider>
        </ColorPickerProvider>
      </body>
    </html>
  );
}
